


PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
PREFIX ipt:  <https://www.in2use.com/process-time/> 
CONSTRUCT {
  ?step gist:precedes ?next .
}
WHERE {
  ?step gist:isPartOf ipt:EmployeeOnboardingTemplate ;
        gist:precedes ?next .
  ?next gist:isPartOf ipt:EmployeeOnboardingTemplate .

  FILTER NOT EXISTS {
    ?step gist:precedes ?middle .
    ?middle gist:isPartOf ipt:EmployeeOnboardingTemplate ;
            gist:precedes ?next .
  }
}


PREFIX gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
PREFIX ipt:  <https://www.in2use.com/process-time/>

CONSTRUCT {
  ?task gist:isPartOf ?project ;
        gist:isBasedOn ?step .
  ?step gist:isPartOf ?process .
  ?project gist:isBasedOn ?process .
}
WHERE {
  VALUES ?project { ipt:AlexOnboardingProject }

  ?project gist:isBasedOn ?process .
  ?task gist:isPartOf ?project ;
        gist:isBasedOn ?step .
  ?step gist:isPartOf ?process .
}